### ISSUE TITLE
Disable Sound for Messages not Working

### ISSUE THREAD

**Issue by michaeljajou** [cometchat/cometchat-chat-sample-app-flutter#25]
When specifying `disableSoundForMessages` inside the CometChatMessages widget - the sound for messages is still being played. 

```
    return Container(
      color: Colors.white,
      child: cc.CometChatMessages(
        theme: cc.CometChatTheme(
          palette: CometTheme.palette,
          typography: cc.Typography.fromDefault(),
        ),
        user: cc.User(
          uid: 'SUPERHERO3',
          name: 'Jake M.',
          status: 'Away',
        ),
        // messageHeaderConfiguration: CometTheme.messageHeaderConfiguration,
        disableSoundForMessages: true,
        messageComposerView: CometTheme.composerView,
      ),
    );
```

```
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  go_router: ^10.0.0
  flutter_bloc: ^8.1.3
  freezed: ^2.4.2
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  permission_handler: 10.2.0
  flutter_svg: ^2.0.7
  image_picker: ^1.0.4
  app_settings: ^5.0.0
  webview_flutter: ^4.2.4
  url_launcher: ^6.1.14
  equatable: ^2.0.5
  flutter_dotenv: ^5.1.0
  shared_preferences: ^2.2.2
  email_validator: ^2.1.17
  camera: ^0.10.5+8
  collection: ^1.18.0
  share_plus: ^7.2.1
  intl: ^0.18.1
  cometchat_chat_uikit: ^4.1.0
  google_fonts: ^4.0.4
  image_cropper: ^4.0.1
  get: ^4.6.6
  cometchat_calls_uikit: ^4.1.0
  animated_text_kit: ^4.2.2
  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
```
